### ISSUE TITLE
Enhancement - tmpreaper on Ubuntu

### ISSUE THREAD

**Issue by hbokh** [cytopia/mysqldump-secure#11]
This really made my day, thanks heaps for this solution!
I altered the script locally to make use of "tmpreaper" on Ubuntu, since "tmpwatch" is unavailable. The used options remain the same.
Maybe it's possible to include this as an option in a next release?

**Comment by cytopia** [comment]
Can you post the changes you made, so I can have a look at it.
Is tmpwatch generally unavailable on Ubuntu?

**Comment by hbokh** [comment]
Here is a diff: https://gist.github.com/hbokh/f56c253e9064d923cde1 

This morning it turned out I also had to put in a PATH-line, since `/usr/sbin/tmpreaper` was not found by the script AND also had to include a `-f` (force) to delete older files:
```
2015-08-05 09:14:01 Non-writeable file, owned by UID (0) skipped: `2015-08-04_2015__database.sql.gz.enc'
```

Hope this helps.

**Comment by cytopia** [comment]
I added the tmpreaper integration into the develop branch.

For the `-f` issue, I will need to do some research before implementing it as a default option.

**Comment by cytopia** [comment]
Added in master branch and scheduled for next release
