### ISSUE TITLE
mysqldump hogging CPU and I/O

### ISSUE THREAD

**Issue by jk2021** [cytopia/mysqldump-secure#19]
Is it possible to add “nice” feature, to help the backups not hog the CPU and IO?

**Comment by cytopia** [comment]
Hi @jk2021 ,

As I have read `nice` is not required to be issued on the commands inside the script.
It is sufficient to start `mysqldump-secure` with `nice` prefixed.

See here

* http://www.linuxforums.org/forum/newbie/96715-using-nice-script.html#post479756
* https://superuser.com/questions/451410/does-the-linux-nice-command-work-on-any-shell-script

`nice` will be inherited by the commands inside the script.

So simply do

`nice 10 mysqldump-secure`

**Comment by cytopia** [comment]
I am closing this ticket now, as `nice`/`renice` is not required inside the script in order to be used.

```shell
$ nice 10 mysqldump-secure
```
