### ISSUE TITLE
cron

### ISSUE THREAD

**Issue by Tntdruid** [cytopia/mysqldump-secure#22]
Hello,

The cron never run on my server used this command:

mysqldump-secure --cron

Works fine if i run it manuel

**Comment by cytopia** [comment]
Maybe it is not in your path.
Can you specify the full path, e.g. `/usr/local/bin/mysqldump-secure --cron` within your crontab.

Also could u show your current crontab.

**Comment by Tntdruid** [comment]
crontab -l
0 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null

Thats all i got there :)

**Comment by cytopia** [comment]
I don't see any `mysqldump-secure` in your cron.
Is that in `/root/.acme.sh` ? If so, could u paste that then.

You would need to directly specify `/usr/bin/mysqldump-secure --cron`.

Also which version of mysqldump-secure are you using? (`/usr/bin/mysqldump-secure --version`)

**Comment by Tntdruid** [comment]
/root/.acme.sh is https://github.com/Neilpang/acme.sh

# /usr/bin/mysqldump-secure --version
Name:    mysqldump-secure
Version: 0.16.3 (2016-08-18)
Author:  Patrick Plocke <patrick@plocke.de> (0x28BF179F)
Code:    https://github.com/cytopia/mysqldump-secure
URL:     http://mysqldump-secure.org
License: MIT

i can run mysqldump-secure just fine whit no path

**Comment by cytopia** [comment]
Ok, I thought `.acme.sh` starts `mysqldump-secure` from cron.

Anyway, where is your cron command for `mysqldump-secure` then (output of `crontab -l` only shows your `.acme.sh` script).

It should be something like
```
0 0 * * * /usr/bin/mysqldump-secure --cron
```

**Comment by Tntdruid** [comment]
I never get added when i run mysqldump-secure --cron

Should i add it manual then?

**Comment by cytopia** [comment]
Yes, you will need to add that command manually.
The `--cron` option simply disables any `stdout` messages and will only ever display `stderr`.
So in case of warnings or errors you will receive a cron email in your root account.

**Comment by cytopia** [comment]
I will close this now as there was just some confusion about how to set this up.
