### ISSUE TITLE
[ERROR] mysqldump-secure: 1937: return: Illegal number:

### ISSUE THREAD

**Issue by dattapw** [cytopia/mysqldump-secure#32]
Using devilbox. Tried running mysqldump-secure. Got error. Re-installed devilbox, imported SQL backup. Still getting the error. Please help.

> devilbox@php-7.3.16 in /shared/httpd $ mysqldump-secure -v
[DEBUG] (CFG): Using config: /etc/mysqldump-secure.conf
[INFO]  (OPT): Logging enabled
[DEBUG] (OPT): Log level: 2
[DEBUG] (OPT): Log file: /var/log/mysqldump-secure.log
[DEBUG] (CFG): Destination dir: /shared/backups/mysql
[DEBUG] (CFG): Using file Prefix: 2020-06-24_10-43__
[INFO]  (OPT): MySQL SSL connection disabled
[INFO]  (OPT): Compression enabled
[DEBUG] (OPT): Compression arguments: gzip -9 -c
[INFO]  (OPT): Encryption disabled
[INFO]  (OPT): Deletion disabled
[INFO]  (OPT): Nagios log disabled
[INFO]  (OPT): Info files enabled
[DEBUG] (SRV): MySQL server connection: mysql via TCP/IP
[DEBUG] (SRV): MySQL server connection: Not using SSL (plain).
[DEBUG] (SRV): MySQL server rep type:   master
[DEBUG] (SRV): MySQL server version:    MySQL 8.0.19 MySQL Community Server - GPL
[DEBUG] (SRV): MySQL server hostname:   mysql:3306
[DEBUG] (SQL): Retrieving list of databases...  5
/usr/local/bin/mysqldump-secure: 1937: return: Illegal number:

**Comment by fibis** [comment]
Will there be a fix for this in the near future?

**Comment by robots4life** [comment]
?

**Comment by fibis** [comment]
Am So., Feb. 6, 2022 at 14:06 schrieb ***@***.***>:   


?

**Comment by jrbecart** [comment]
Since the fix was never released, to fix it yourself just change the line: 1930
from
`
_query="SELECT IF(COUNT(*) = 0, '0', '1') AS empty
`
to
`
_query="SELECT IF(COUNT(*) = 0, '0', '1') AS is_empty
`

Then 
```shell
./configure
make
sudo make reinstall
```

**Comment by muratyarali** [comment]
what is the latest progress on this error? I am getting same one.
